### ISSUE TITLE
design a logo

### ISSUE THREAD

**Issue by chandansgowda** [Sparsh752/E-Rickshaw#19]
The application now looks very plain since it has no logo or icon which can be used while building screens etc. It would be great to create a logo for the app.

**Comment by Sparsh752** [comment]
@chandansgowda Would you like to work on this issue?

**Comment by chandansgowda** [comment]
Hey @Sparsh752
I'm not actually a designer. I would be happy to contribute to the codebase.

**Comment by Tushar98644** [comment]
can i take up the issue if no is assigned ? @Sparsh752

**Comment by Sparsh752** [comment]
@Tushar98644 Ok I will assign this to you
