### ISSUE TITLE
Implement switching between dark mode and light mode in the app....

### ISSUE THREAD

**Issue by Tushar98644** [Sparsh752/E-Rickshaw#20]

**Comment by Tushar98644** [comment]
@Sparsh752 assign me this...

**Comment by Sparsh752** [comment]
@Tushar98644 Ok you can work on this issue

**Comment by Tushar98644** [comment]
> @Tushar98644 Can you collaborate with kunj shukla who is working on improving the UI

already submitted another pr .....do some other changes need to be made?
no issues on working with him tho....

**Comment by kunjshukla** [comment]
Assign me

**Comment by Sparsh752** [comment]
@Tushar98644 The dark mode looks dope! @kunjshukla could help you with some UI ideas, as he was working on improving the UI. Also I want the design to be consistent.

**Comment by Sparsh752** [comment]
@Tushar98644 I would also give you bonus points

**Comment by Sparsh752** [comment]
@Tushar98644 Also I would give you as much time as you want? PR the 3 issues together all at once.

**Comment by Sparsh752** [comment]
@Tushar98644 PS The logos also look good

**Comment by Tushar98644** [comment]
> @Tushar98644 PS The logos also look good



> @Tushar98644 Also I would give you as much time as you want? PR the 3 issues together all at once.

sure ....i will cooperate with him and pr all the issues together

**Comment by Sparsh752** [comment]
@kunjshukla Also it would be better if you recommend design which goes with the logos.

**Comment by Sparsh752** [comment]
@kunjshukla @Tushar98644 You can exchange numbers or discuss on any platform you need

**Comment by kunjshukla** [comment]
@Tushar98644 u can msg me on 99782 10511

**Comment by Tushar98644** [comment]
> @Tushar98644 u can msg me on 99782 10511
ok...

**Comment by kunjshukla** [comment]
This is done.!

**Comment by kunjshukla** [comment]
The issue is completed. My contributions:
1. Suggesting the UI
2. Setting up the background color, button color in light mode and dark mode.
