### ISSUE TITLE
Add Email verification on sign up pages

### ISSUE THREAD

**Issue by Sparsh752** [Sparsh752/E-Rickshaw#3]
On signing up users should verify their email before. An email should be sent to their email ids and only after verification, they should be signed up.

**Comment by Adittya-Gupta** [comment]
Hey @Sparsh752 I think I can work on this issue. Plz assign it to me

**Comment by Sparsh752** [comment]
> Hey @Sparsh752 I think I can work on this issue. Plz assign it to me

@Adittya-Gupta Thanks for showing interest in this issue. You can work on this as I have assigned this issue to you.

**Comment by Sparsh752** [comment]
@Adittya-Gupta Nice Work! I have merged your pr. Soon will update the points
