### ISSUE TITLE
Add forgot password textbutton on sign in pages

### ISSUE THREAD

**Issue by Sparsh752** [Sparsh752/E-Rickshaw#5]
Add forgot password text button on driver and passenger sign-in pages. Also on pressing them, the user should be pushed to the Forgot Password Page which is yet to be made
![image](https://user-images.githubusercontent.com/94468600/205513469-20994599-977c-45d1-92b6-3fc6254974c6.png)
A simple button just like this

**Comment by Tushar98644** [comment]
I would like to work on this issue

**Comment by Sparsh752** [comment]
> I would like to work on this issue

@Tushar98644 I have assigned this issue to you, you can start working on it now.
If you want any clarification, you can always ask me.

**Comment by Sparsh752** [comment]
@Tushar98644 the page for Forgot password doesn't exists, so please make a Forgot Password page

**Comment by Sparsh752** [comment]
@Tushar98644 please only commit the files you have changed. Please make another pull request

**Comment by Sparsh752** [comment]
<img width="1116" alt="Screenshot 2022-12-06 at 16 57 54" src="https://user-images.githubusercontent.com/94468600/205899908-4f232c0f-ed74-4445-b11f-4a78138c6a0d.png">
It showing that you have changed a lot of files

**Comment by Tushar98644** [comment]
ok i am adding only the changed files

**Comment by Tushar98644** [comment]
> @Tushar98644 ok, your work has been merged. Thank you for contributing.

when will my points be assigned for resolving the issue in codepeak?

**Comment by Sparsh752** [comment]
@Tushar98644 I will update it shortly

**Comment by Tushar98644** [comment]
> @Tushar98644 I have added the points

Thank you ...when will new issues get added ?
