### ISSUE TITLE
Add screenshots of the App on the README.md

### ISSUE THREAD

**Issue by Sparsh752** [Sparsh752/E-Rickshaw#7]
Inside the ReadMe file add the screenshots of the app under an appropriate heading. Follow the instructions on the README.md file to clone this repository. Make sure you have flutter installed on your system.

**Comment by Yash-jar** [comment]
@Sparsh752  I want to work on this issue. Please assign it to me.

**Comment by Sparsh752** [comment]
@Yash-jar Thanks for showing interest in this issue. I have assigned it to you, you may start working.
